In [600]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [601]:
import matplotlib.pyplot as plt
import json
from web3 import Web3
# ganache_url = "https://ropsten.infura.io/v3/6072fdc3b95c407caa681f63ebaf72b8"
ganache_url ="http://127.0.0.1:8545"
web3 = Web3(Web3.HTTPProvider(ganache_url))
web3.isConnected()

True

In [602]:

# abi_triple = json.loads('[ { "constant": false, "inputs": [ { "name": "Prior0", "type": "int256" }, { "name": "Prior1", "type": "int256" }, { "name": "Prior2", "type": "int256" } ], "name": "e_exponent1", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "d_printparamaters2", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "c_printparamaters1", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "d_printparamaters3", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [ { "name": "x1", "type": "int256" }, { "name": "x2", "type": "int256" }, { "name": "x3", "type": "int256" }, { "name": "x4", "type": "int256" }, { "name": "v1", "type": "int256" }, { "name": "v2", "type": "int256" }, { "name": "v3", "type": "int256" }, { "name": "v4", "type": "int256" }, { "name": "m1", "type": "int256" }, { "name": "m2", "type": "int256" }, { "name": "m3", "type": "int256" }, { "name": "m4", "type": "int256" } ], "name": "b_getparameters3", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [ { "name": "x1", "type": "int256" }, { "name": "x2", "type": "int256" }, { "name": "x3", "type": "int256" }, { "name": "x4", "type": "int256" }, { "name": "v1", "type": "int256" }, { "name": "v2", "type": "int256" }, { "name": "v3", "type": "int256" }, { "name": "v4", "type": "int256" }, { "name": "m1", "type": "int256" }, { "name": "m2", "type": "int256" }, { "name": "m3", "type": "int256" }, { "name": "m4", "type": "int256" } ], "name": "a_getparameters1", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "f_compare", "outputs": [ { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [ { "name": "x1", "type": "int256" }, { "name": "x2", "type": "int256" }, { "name": "x3", "type": "int256" }, { "name": "x4", "type": "int256" }, { "name": "v1", "type": "int256" }, { "name": "v2", "type": "int256" }, { "name": "v3", "type": "int256" }, { "name": "v4", "type": "int256" }, { "name": "m1", "type": "int256" }, { "name": "m2", "type": "int256" }, { "name": "m3", "type": "int256" }, { "name": "m4", "type": "int256" } ], "name": "b_getparameters2", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" } ]')
abi_triple = json.loads('[ { "constant": true, "inputs": [], "name": "print", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [ { "name": "Prior0", "type": "int256" }, { "name": "Prior1", "type": "int256" }, { "name": "Prior2", "type": "int256" } ], "name": "e_exponent1", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "d_printparamaters2", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "c_printparamaters1", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "d_printparamaters3", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [ { "name": "x1", "type": "int256" }, { "name": "x2", "type": "int256" }, { "name": "x3", "type": "int256" }, { "name": "x4", "type": "int256" }, { "name": "v1", "type": "int256" }, { "name": "v2", "type": "int256" }, { "name": "v3", "type": "int256" }, { "name": "v4", "type": "int256" }, { "name": "m1", "type": "int256" }, { "name": "m2", "type": "int256" }, { "name": "m3", "type": "int256" }, { "name": "m4", "type": "int256" } ], "name": "b_getparameters3", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [ { "name": "x1", "type": "int256" }, { "name": "x2", "type": "int256" }, { "name": "x3", "type": "int256" }, { "name": "x4", "type": "int256" }, { "name": "v1", "type": "int256" }, { "name": "v2", "type": "int256" }, { "name": "v3", "type": "int256" }, { "name": "v4", "type": "int256" }, { "name": "m1", "type": "int256" }, { "name": "m2", "type": "int256" }, { "name": "m3", "type": "int256" }, { "name": "m4", "type": "int256" } ], "name": "a_getparameters1", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "f_compare", "outputs": [ { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [ { "name": "x1", "type": "int256" }, { "name": "x2", "type": "int256" }, { "name": "x3", "type": "int256" }, { "name": "x4", "type": "int256" }, { "name": "v1", "type": "int256" }, { "name": "v2", "type": "int256" }, { "name": "v3", "type": "int256" }, { "name": "v4", "type": "int256" }, { "name": "m1", "type": "int256" }, { "name": "m2", "type": "int256" }, { "name": "m3", "type": "int256" }, { "name": "m4", "type": "int256" } ], "name": "b_getparameters2", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" } ]')
cont_address_triple = '0x12b8325b407eAf9ED48a97A36Bd3239F68a69999'
contract_triple = web3.eth.contract(address=cont_address_triple,abi=abi_triple)

account_1 = "0x37bfB436392DaAE0E91EdcD9c4128FBcADF3919d"
private_key1 = "e72044de2331844a3c0232dc23d43fb8ca4f555854b4da07e2fb530d003e5e2d"
account_2 = "0xfbD8f1F5878b0b5b3E627e7cc14617b05B582867"
private_key2="56c8f569b23a423f9d66d46f86f7ada7ba0d28dfba03c34f661bb15358b042bb"

In [603]:
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')
# X = dataset.iloc[:,:4].values
# y = dataset['species'].values
dataset.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [604]:
dataset["sepal_length"] = dataset["sepal_length"]*10
dataset["sepal_width"] = dataset["sepal_width"]*10
dataset["petal_length"] = dataset["petal_length"]*10
dataset["petal_width"] = dataset["petal_width"]*10
dataset[:150]

sepal_length  sepal_width  petal_length  petal_width    species
0            51.0         35.0          14.0          2.0     setosa
1            49.0         30.0          14.0          2.0     setosa
2            47.0         32.0          13.0          2.0     setosa
3            46.0         31.0          15.0          2.0     setosa
4            50.0         36.0          14.0          2.0     setosa
..            ...          ...           ...          ...        ...
145          67.0         30.0          52.0         23.0  virginica
146          63.0         25.0          50.0         19.0  virginica
147          65.0         30.0          52.0         20.0  virginica
148          62.0         34.0          54.0         23.0  virginica
149          59.0         30.0          51.0         18.0  virginica

[150 rows x 5 columns]

In [605]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
label_encoder = preprocessing.LabelEncoder()
dataset['species']= label_encoder.fit_transform(dataset['species']) 
dataset['species'].unique()

array([0, 1, 2])

In [606]:
X = dataset.iloc[:,:4].values
y = dataset['species'].values

In [607]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [608]:
X_train

array([[57., 38., 17.,  3.],
       [66., 30., 44., 14.],
       [59., 30., 51., 18.],
       [65., 30., 52., 20.],
       [46., 31., 15.,  2.],
       [48., 31., 16.,  2.],
       [51., 34., 15.,  2.],
       [62., 22., 45., 15.],
       [51., 38., 15.,  3.],
       [51., 38., 16.,  2.],
       [61., 26., 56., 14.],
       [57., 30., 42., 12.],
       [63., 34., 56., 24.],
       [57., 26., 35., 10.],
       [65., 32., 51., 20.],
       [65., 30., 55., 18.],
       [57., 28., 45., 13.],
       [55., 35., 13.,  2.],
       [77., 38., 67., 22.],
       [50., 32., 12.,  2.],
       [63., 33., 60., 25.],
       [62., 34., 54., 23.],
       [63., 25., 50., 19.],
       [56., 25., 39., 11.],
       [61., 28., 47., 12.],
       [60., 22., 50., 15.],
       [55., 42., 14.,  2.],
       [44., 30., 13.,  2.],
       [60., 29., 45., 15.],
       [50., 36., 14.,  2.],
       [49., 24., 33., 10.],
       [61., 30., 49., 18.],
       [67., 31., 56., 24.],
       [77., 26., 69., 23.],
       [50., 3

In [609]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

In [610]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [611]:
y_pred = classifier.predict(X_test) 
y_pred

array([2, 0, 0, 2, 1, 2, 1, 1, 2, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1, 1,
       2, 1, 1, 2, 2, 1, 2, 2])

In [612]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  0.9666666666666667


array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  1, 10]], dtype=int64)

In [613]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.91      1.00      0.95        10
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [614]:
y_test

array([2, 0, 0, 2, 1, 2, 1, 1, 2, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1, 1,
       2, 1, 1, 2, 2, 2, 2, 2])

In [615]:
dataset = dataset.astype(int)

dataset = dataset.sample(frac=1)
dataset.head()

sepal_length  sepal_width  petal_length  petal_width  species
38            44           30            13            2        0
63            61           29            47           14        1
11            48           34            16            2        0
82            58           27            39           12        1
58            66           29            46           13        1

In [616]:
X1 = dataset[:120]
X2 = dataset[120:]

In [617]:
X2

sepal_length  sepal_width  petal_length  petal_width  species
107            73           29            63           18        2
121            56           28            49           20        2
70             59           32            48           18        1
142            58           27            51           19        2
14             58           40            12            2        0
40             50           35            13            3        0
42             44           32            13            2        0
46             51           38            16            2        0
110            65           32            51           20        2
83             60           27            51           16        1
132            64           28            56           22        2
130            74           28            61           19        2
84             54           30            45           15        1
108            67           25            58           18        2
39             51           34            15            2        0
78             60           29            45           15        1
35             50           32            12            2        0
71             61           28            40           13        1
128            64           28            56           21        2
31             54           34            15            4        0
145            67           30            52           23        2
45             48           30            14            3        0
101            58           27            51           19        2
146            63           25            50           19        2
127            61           30            49           18        2
139            69           31            54           21        2
24             48           34            19            2        0
59             52           27            39           14        1
133            63           28            51           15        2
104            65           30            58           22        2

In [618]:
X1_class0 = X1.loc[X1['species'] == 0]
X1_class1 = X1.loc[X1['species'] == 1]
X1_class2 = X1.loc[X1['species'] == 2]


In [619]:
f1_mean_0 = X1_class0['sepal_length'].mean().astype(int).item()
f2_mean_0 = X1_class0['sepal_width'].mean().astype(int).item()
f3_mean_0 = X1_class0['petal_length'].mean().astype(int).item()
f4_mean_0 = X1_class0['petal_width'].mean().astype(int).item()
f1_var_0 = X1_class0['sepal_length'].var().astype(int).item()
f2_var_0 = X1_class0['sepal_width'].var().astype(int).item()
f3_var_0 = X1_class0['petal_length'].var().astype(int).item()
f4_var_0 = X1_class0['petal_width'].var().astype(int).item()

In [620]:
f1_mean_1 = X1_class1['sepal_length'].mean().astype(int).item()
f2_mean_1 = X1_class1['sepal_width'].mean().astype(int).item()
f3_mean_1 = X1_class1['petal_length'].mean().astype(int).item()
f4_mean_1 = X1_class1['petal_width'].mean().astype(int).item()
f1_var_1 = X1_class1['sepal_length'].var().astype(int).item()
f2_var_1 = X1_class1['sepal_width'].var().astype(int).item()
f3_var_1 = X1_class1['petal_length'].var().astype(int).item()
f4_var_1 = X1_class1['petal_width'].var().astype(int).item()

In [621]:
f1_mean_2 = X1_class2['sepal_length'].mean().astype(int).item()
f2_mean_2 = X1_class2['sepal_width'].mean().astype(int).item()
f3_mean_2 = X1_class2['petal_length'].mean().astype(int).item()
f4_mean_2 = X1_class2['petal_width'].mean().astype(int).item()
f1_var_2 = X1_class2['sepal_length'].var().astype(int).item()
f2_var_2 = X1_class2['sepal_width'].var().astype(int).item()
f3_var_2 = X1_class2['petal_length'].var().astype(int).item()
f4_var_2 = X1_class2['petal_width'].var().astype(int).item()

In [622]:
print(f1_mean_0,f2_mean_0,f3_mean_0,f4_mean_0,f1_var_0,f2_var_0,f3_var_0,f4_var_0)

49 34 14 2 12 15 2 1


In [623]:
print(f1_mean_1,f2_mean_1,f3_mean_1,f4_mean_1,f1_var_1,f2_var_1,f3_var_1,f4_var_1)

59 27 42 13 28 10 22 3


In [624]:
print(f1_mean_2,f2_mean_2,f3_mean_2,f4_mean_2,f1_var_2,f2_var_2,f3_var_2,f4_var_2)

66 30 56 20 46 12 34 8


In [625]:
X1["species"].value_counts()


1    44
0    41
2    35
Name: species, dtype: int64

In [626]:
prior0 = int((40/120)*100)
prior1 = int((38/120)*100)
prior2 = int((42/120)*100)

In [627]:
X_test = X2.values
y_test_sc = X2["species"].values

In [628]:
y_pred

array([2, 0, 0, 2, 1, 2, 1, 1, 2, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1, 1,
       2, 1, 1, 2, 2, 1, 2, 2])

In [629]:
y_test_sc

array([2, 2, 1, 2, 0, 0, 0, 0, 2, 1, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 0,
       2, 2, 2, 2, 0, 1, 2, 2])

In [630]:
# y_pred_sc = np.array([1,2,0,2,1,0,1,2,2,1,0,1,0,1,2,1,0,1,1,2,0,0,2,1,2,1,0,0,2,1])

# print ("Accuracy : ", accuracy_score(y_test, y_pred_sc))

In [631]:
# print ("Accuracy : ", accuracy_score(y_test, y_pred))
# print ("Accuracy : ", accuracy_score(y_test, y_pred_sc))

In [632]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.91      1.00      0.95        10
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [633]:
# print(classification_report(y_test, y_pred_sc))

In [634]:
# For triple
def triple_send_txn(a1,a2,a3,a4,b1,b2,b3,b4,c1,c2,c3,c4,\
                    e1,e2,e3,e4,f1,f2,f3,f4,g1,g2,g3,g4,\
                    h1,h2,h3,h4,i1,i2,i3,i4,j1,j2,j3,j4,\
                    d1,d2,d3,account1,account2,privatekey1,privatekey2):
    nonce = web3.eth.getTransactionCount(account1)
    transaction = contract_triple.functions.a_getparameters1(
        a1,a2,a3,a4,b1,b2,b3,b4,c1,c2,c3,c4
         ).buildTransaction({
        'gas': 3000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account1,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey1)
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
#     print(tx_receipt.gasUsed)
    nonce = web3.eth.getTransactionCount(account2)
    transaction = contract_triple.functions.b_getparameters2(
        e1,e2,e3,e4,f1,f2,f3,f4,g1,g2,g3,g4
         ).buildTransaction({
        'gas': 3000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account2,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey2)
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
#     print(tx_receipt.gasUsed)
    nonce = web3.eth.getTransactionCount(account1)
    transaction = contract_triple.functions.b_getparameters3(
        h1,h2,h3,h4,i1,i2,i3,i4,j1,j2,j3,j4
         ).buildTransaction({
        'gas': 3000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account1,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey1)
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
#     print(tx_receipt.gasUsed)
    
#     nonce = web3.eth.getTransactionCount(account2)
#     transaction = contract_triple.functions.b_getparameters3(
#         a1,a2,a3,a4,b1,b2,b3,b4,c1,c2,c3,c4
#          ).buildTransaction({
#         'gas': 3000000,
#         'gasPrice': web3.toWei('10', 'gwei'),
#         'from': account2,
#         'nonce': nonce
#         }) 
#     signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey2)
#     tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
#     tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
#     print(tx_receipt.gasUsed)
    
    nonce = web3.eth.getTransactionCount(account1)
    transaction = contract_triple.functions.e_exponent1(
        d1,d2,d3
         ).buildTransaction({
        'gas': 3000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account1,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey1)
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
#     print(tx_receipt.gasUsed)
    
#     nonce = web3.eth.getTransactionCount(account1)
#     transaction = contract_triple.functions.e_exponent(
#         a1,a2,a3,a4,b1,b2,b3,b4,c1,c2
#          ).buildTransaction({
#         'gas': 3000000,
#         'gasPrice': web3.toWei('10', 'gwei'),
#         'from': account1,
#         'nonce': nonce
#         }) 
#     signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey1)
#     tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
#     tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
#     print(tx_receipt.gasUsed)
    print(contract_triple.functions.print().call())
    return (contract_triple.functions.f_compare().call())
    


In [635]:
# triple_send_txn(1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,account_1,account_2,private_key1,private_key2)

In [636]:
pred =[]
for i in range(len(y_test)):
    f1 = X_test[i][0].item();f2 = X_test[i][1].item(); f3 =X_test[i][2].item(); f4 =X_test[i][4].item()
    
    pred.append(triple_send_txn(f1,f2,f3,f4,f1_var_0,f2_var_0,f3_var_0,f4_var_0,f1_mean_0,f2_mean_0,f3_mean_0,f4_mean_0,\
                                f1,f2,f3,f4,f1_var_1,f2_var_1,f3_var_1,f4_var_1,f1_mean_1,f2_mean_1,f3_mean_1,f4_mean_1,\
                                f1,f2,f3,f4,f1_var_2,f2_var_2,f3_var_2,f4_var_2,f1_mean_2,f2_mean_2,f3_mean_2,f4_mean_2,\
                                prior0,prior1,prior2,account_1,account_2,private_key1,private_key2))
    

[0, 6783603908724342360427305369600000000, 1568547773500739284358167265280000000000]
[0, 6783603908724342360427305369600000000000, 1065690726717576465858145812480000000]
[0, 6783603908724342360427305369600000000, 1691878134194677329735482081280000000000]
[0, 6783603908724342360427305369600000000, 1695539692473207544039216250880000000000]
[7687143243080966524979537510400000000000, 0, 20157993199418076463104000000000000]
[7687143243080966524979537510400000000000, 0, 16916333983577561943244800000000000]
[7687143243080966524979537510400000000000, 0, 16206758716631688922382991360000000]
[7687143243080966524979537510400000000000, 0, 19794796063562572826998210560000000]
[0, 6783603908724342360427305369600000000, 1435399326221581757256491335680000000000]
[0, 6783603908724342360427305369600000000, 1215057845772403890947862036480000000000]
[0, 6783603908724342360427305369600000000, 2649916182112036740282061946880000000000]
[0, 6783603908724342360427305369600000000, 118236794906417831220093124608

In [637]:
pred

[2,
 1,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 1,
 2,
 0,
 2,
 0,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 0,
 1,
 2,
 2]

In [638]:
y_test_sc

array([2, 2, 1, 2, 0, 0, 0, 0, 2, 1, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 0,
       2, 2, 2, 2, 0, 1, 2, 2])

In [639]:
print(classification_report(pred,y_test_sc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.50      0.75      0.60         4
           2       0.93      0.82      0.87        17

    accuracy                           0.87        30
   macro avg       0.81      0.86      0.83        30
weighted avg       0.90      0.87      0.88        30



In [640]:
print(accuracy_score(pred,y_test_sc))

0.8666666666666667
