## Loading the Dataset

In [1]:
import numpy as np
import pandas as pd


from sklearn.decomposition import PCA as RandomizedPCA
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
                        

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
# from sklearn.decomposition import PCA
# pca =PCA(n_components =2)
# principalComponents = pca.fit_transform(x_norm)
# pdf = pd.DataFrame(data=principalComponents, columns = ['pc1', 'pc2'])
# pdf

In [3]:
# finaldf = pd.concat([pdf,df[['target']]], axis =1)
# finaldf.head()

## Train

In [4]:
#NB scikit learn MNIST(60000)
X,y = load_digits(return_X_y=True)

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state =1)
# x_train

In [6]:
# x_train = StandardScaler().fit_transform(x_train)
# x_test = StandardScaler().fit_transform(x_test)

In [7]:
# train_x.shape
x_train.shape

(1437, 64)

In [8]:
x_test

array([[ 0.,  0.,  6., ...,  3.,  0.,  0.],
       [ 0.,  8., 13., ...,  0.,  0.,  0.],
       [ 0.,  0.,  4., ...,  6.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  3., 15., ..., 16., 16.,  2.],
       [ 0.,  0.,  8., ...,  0.,  0.,  0.]])

In [9]:
a = [ 'x_{}'.format(x) for x in range(1,65)]

In [10]:
# df = pd.DataFrame(x_train, columns=a)
# df ['target'] = y_train
# df_mean = df.groupby(['target']).mean()
# df_var = df.groupby(['target']).var()

In [11]:
df = pd.DataFrame(x_train, columns=a).astype(int)
df ['target'] = y_train
df_mean = (df.groupby(['target']).mean()*100).astype(int)
df_var = (df.groupby(['target']).var()*100).astype(int)

In [12]:
df.head()

x_1  x_2  x_3  x_4  x_5  x_6  x_7  x_8  x_9  x_10  ...  x_56  x_57  x_58  \
0    0    0    0    2   15    8    0    0    0     0  ...     0     0     0   
1    0    0    0    7   16   16   11    0    0     0  ...     0     0     0   
2    0    0    0    6   11    0    0    0    0     0  ...     3     0     0   
3    0    0    0    1   12    6    0    0    0     0  ...     0     0     0   
4    0    0    9   11    2    0    0    0    0     8  ...     0     0     0   

   x_59  x_60  x_61  x_62  x_63  x_64  target  
0     0     2    15     5     0     0       4  
1     0    11     3     0     0     0       9  
2     0     5    11    13    12     2       6  
3     0     0    14     9     0     0       4  
4     7     9     9    12     4     0       2  

[5 rows x 65 columns]

In [13]:
df_mean.head()

x_1  x_2  x_3   x_4   x_5  x_6  x_7  x_8  x_9  x_10  ...  x_55  x_56  \
target                                                       ...               
0         0    2  419  1297  1128  299    3    0    0    99  ...   261     0   
1         0    1  245   935  1055  616  114    0    0    10  ...   191    54   
2         0   87  948  1410   954  234   10    0    0   515  ...   737    79   
3         0   59  835  1419  1412  740   74    0    1   405  ...   583     5   
4         0    0   54   734  1139  183   15    6    0     7  ...     2     0   

        x_57  x_58  x_59  x_60  x_61  x_62  x_63  x_64  
target                                                  
0          0     0   412  1366  1345   564    32     0  
1          0     0   217   931  1302   828   278   134  
2          0    92   980  1385  1309  1178   800   190  
3          0    49   922  1469  1392   857   133     6  
4          0     2    67   813  1144   179     0     0  

[5 rows x 64 columns]

In [14]:
df_var.head()

x_1  x_2   x_3   x_4   x_5   x_6  x_7  x_8  x_9  x_10  ...  x_55  \
target                                                         ...         
0         0    5   863   550  1289  1115    3    0    0   382  ...  1061   
1         0    1  1249  3429  2046  3372  521    0    0    17  ...  1321   
2         0  165  2213  1002  2730  1488   28    0    0  1620  ...  2387   
3         0  107  1373   501   635  2449  370    0    1  1388  ...  2112   
4         0    0   246  2400  1794   894  114   45    0    25  ...     2   

        x_56  x_57  x_58  x_59  x_60  x_61  x_62  x_63  x_64  
target                                                        
0          0     0     0   702   413   687  1754   110     0  
1        327     0     0   981  3398  1066  3810  2643  1476  
2        285     0   248  2527  1185  1098  1940  3375  1243  
3         20     0   106  1868   381   878  2011   757    45  
4          0     0     6   375  2866  2030   838     0     0  

[5 rows x 64 columns]

In [15]:
# pca = RandomizedPCA(n_components=10)
# pca.fit(x_train)

# x_train = pca.transform(x_train)
# x_test = pca.transform(x_test)

In [16]:
df_mean = df_mean.values
df_var = df_var.values
for i in range(df_var.shape[0]):
    for j in range(df_var.shape[1]):
        if (df_var[i][j]==0):
            df_var[i][j] = 1

In [17]:
gnb = GaussianNB()
y_pred = gnb.fit(x_train, y_train).predict(x_test)
print("Number of mislabeled points out of a total %d points : %d" % (x_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 360 points : 53
0.8527777777777777


In [18]:
# x_train = StandardScaler().fit_transform(x_train)
# x_test = StandardScaler().fit_transform(x_test)

In [19]:
# gnb = BernoulliNB()
# y_pred = gnb.fit(x_train, y_train).predict(x_test)
# print("Number of mislabeled points out of a total %d points : %d" % (x_test.shape[0], (y_test != y_pred).sum()))
# print(accuracy_score(y_test, y_pred))

In [20]:

# gnb = MultinomialNB()
# y_pred = gnb.fit(x_train, y_train).predict(x_test)
# print("Number of mislabeled points out of a total %d points : %d" % (x_test.shape[0], (y_test != y_pred).sum()))
# print(accuracy_score(y_test, y_pred))

In [21]:
from sklearn.decomposition import PCA
pca =PCA(n_components =10)
pca.fit(x_train,pca)
PC_train = pca.transform(x_train).astype(int)
PC_test = pca.transform(x_test).astype(int)

In [22]:
gnb = GaussianNB()
y_pred = gnb.fit(PC_train, y_train).predict(PC_test)
print("Number of mislabeled points out of a total %d points : %d" % (PC_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 360 points : 35
0.9027777777777778


In [23]:
gnb = BernoulliNB()
y_pred = gnb.fit(PC_train, y_train).predict(PC_test)
print("Number of mislabeled points out of a total %d points : %d" % (PC_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 360 points : 96
0.7333333333333333


## smart contract methods

In [21]:
X, y = load_digits(return_X_y=True)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# x_train = pca.transform(x_train)
# x_test = pca.transform(x_test)
# df = pd.DataFrame(x_train, columns=['f1','f2'])

df = pd.DataFrame(x_train, columns=a)

df ['target'] = y_train
# df_mean = df.groupby(['target']).mean()
df_mean = (df.groupby(['target']).mean()*10).astype(int)
mean = df_mean.values
df_var =  (df.groupby(['target']).var()*10).astype(int)
var = df_var.values

# var

In [22]:
# df_mean = df_mean.values
# df_var = df_var.values
for i in range(var.shape[0]):
    for j in range(var.shape[1]):
        if (var[i][j]==0):
            var[i][j] = 1

In [23]:
dfp = df.groupby('target').size()
cfp = dfp.values
tot = np.sum(cfp)
print(tot)
prior = np.zeros(len(cfp))
for i in range(len(prior)):
    prior[i] = int(cfp[i]/tot *1000)
prior

1437


array([105., 102.,  98., 107., 105.,  98.,  95.,  97.,  93.,  96.])

In [24]:
def mux1(v,k):
    x = 1
#     print(type(v))
    for i in range(len(v)):
        if(i==k): continue
        else:  x = x* v[i]
    return x


def GNB(x,m,v):
    B0=1; C0 =1.0;  A0=1; e = 2.718
    c = np.zeros(len(v));
    for i in range(len(v)):
        B0 = B0* v[i]
        c[i] = (x[i]-m[i])*(x[i]-m[i]) 
    D0 = B0
    for i in range(len(c)):
        C0 = C0+c[i]*mux1(v,i)  
    ex = float(C0/D0)
    out = (A0/B0)*pow(e,-1*ex)
    print("The values of A0, B0, C0, D0 are : ", A0,B0,C0,D0)
    return(out) 

def classification(x,m,v,pt):
    prob = np.zeros(m.shape[0])
    pred = np.zeros(len(y_test))
    z = np.zeros(x.shape[0])
    for i in range(m.shape[0]):
        prob = np.zeros(m.shape[0])
        for j in range(x.shape[0]):
            print("the data are  ", x[j], m[i], v[i], pt[i])
            prob[i] = GNB(x[j],m[i],v[i]) * pt[i]        
        print("probabilities are ",prob)
        pred[i] =np.argmax(prob)
    print("prediction classes are ",pred)
    return pred

In [25]:
# pred = classification (x_test[:1],mean,var,prior)
# pred
x = list(x_test[:1,:14].astype(int))
m = list(mean[:1,:14])
v = list(var[:1,:14])
print(x,',',m,',',v)

[array([ 0,  0, 11, 16, 15,  3,  0,  0,  0,  5, 16, 12, 11, 13])] , [array([  0,   0,  41, 129, 112,  29,   0,   0,   0,   9, 125, 136, 116,
       112])] , [array([  1,   1,  87,  52, 126, 110,   1,   1,   1,  35, 120,  90, 167,
       120])]


In [26]:
mean[:1,:2]

array([[0, 0]])

In [27]:
GNB(x,m,v)

ValueError: setting an array element with a sequence.

In [28]:
import matplotlib.pyplot as plt
import json
from web3 import Web3
ganache_url = "https://ropsten.infura.io/v3/6072fdc3b95c407caa681f63ebaf72b8"
# ganache_url ="http://127.0.0.1:8545"
web3 = Web3(Web3.HTTPProvider(ganache_url))
web3.isConnected()

True

In [29]:
abi = json.loads('[ { "constant": false, "inputs": [ { "name": "x", "type": "int256[]" }, { "name": "m", "type": "int256[]" }, { "name": "v", "type": "int256[]" } ], "name": "a_getparameters1", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [ { "name": "e0", "type": "int256" }, { "name": "e1", "type": "int256" }, { "name": "f0", "type": "int256" }, { "name": "f1", "type": "int256" }, { "name": "g0", "type": "int256" }, { "name": "g1", "type": "int256" }, { "name": "h0", "type": "int256" }, { "name": "h1", "type": "int256" }, { "name": "Prior0", "type": "int256" }, { "name": "Prior1", "type": "int256" } ], "name": "e_exponent", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "set_exponent", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "a_setparameters1", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [ { "name": "v", "type": "int256[]" }, { "name": "k", "type": "uint256" } ], "name": "mux", "outputs": [ { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "nonpayable", "type": "function" } ]')
cont= '0xdF8fC5B4aBda9e2756e9C914a708aAF8f32714FD'
contract_triple = web3.eth.contract(address=cont,abi=abi)

account1 = "0xdd617f9D5120b7b30E4C502fdd6b13dCf286A300"
privatekey1 = "c00b36dc1777e7fda60ff1f55b57c3f51b18c0c16fe44724e451ed062a173d74"
account2 = "0x8883f1016E727C8fE93C1Df471f102bBbAF2B910"
privatekey2="8d70f54549b5fb7c04fc016cc88c447fc81aff3af3065c696aee1b529fbc8ba5"

In [30]:
def triple_send_txn(a,b,c,account1,account2,privatekey1,privatekey2):
    nonce = web3.eth.getTransactionCount(account2)
    transaction = contract_triple.functions.a_getparameters1(
        a,b,c
         ).buildTransaction({
        'gas': 3000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account2,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey2)
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    return tx_receipt.gasUsed

In [35]:
# for i in range(1,64):
#     x = x_test[1,:i].astype(int).tolist()
#     m = mean[1,:i].tolist()
#     v = var[1,:i].tolist()
#     print(x,',',m,',',v)

In [313]:
type(m)

list

In [314]:
z = np.array2string(x_test[1,:3].astype(int), precision=2, separator=',',suppress_small=True)
z

'[ 0, 1,15]'

In [315]:
gas=[]
for i in range(1,64):
    x = x_test[1,:i].astype(int).tolist()
    m = mean[1,:i].tolist()
    v = var[1,:i].tolist()
    print(type(x))
    print(x,m,v)
    gas.append(triple_send_txn(x,m,v,account1,account2,privatekey1,privatekey2))
    print("transaction number:",i)

<class 'list'>
[0] [0] [1]
transaction number: 1
<class 'list'>
[0, 1] [0, 0] [1, 1]
transaction number: 2
<class 'list'>
[0, 1, 15] [0, 0, 25] [1, 1, 126]
transaction number: 3
<class 'list'>
[0, 1, 15, 14] [0, 0, 25, 93] [1, 1, 126, 338]
transaction number: 4
<class 'list'>
[0, 1, 15, 14, 2] [0, 0, 25, 93, 105] [1, 1, 126, 338, 195]
transaction number: 5
<class 'list'>
[0, 1, 15, 14, 2, 0] [0, 0, 25, 93, 105, 60] [1, 1, 126, 338, 195, 321]


ValueError: {'code': -32000, 'message': 'nonce too low'}

In [316]:
gas

[194312, 224494, 269799, 313928, 362959]