## Loading the Dataset

In [20]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import json
from web3 import Web3
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
df = pd.read_csv(url, names=['sepal length','sepal width', 'petal length', 'petal width', 'target'])
# df['target']                             

## Normalizing Dataset 

In [4]:

X,y = load_iris(return_X_y=True)
features =['sepal length', 'sepal width', 'petal length', 'petal width']
x = df.loc[:, features].values
y = df.loc[:, ['target']].values
x_norm = StandardScaler().fit_transform(x)
# x_norm

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 30 points : 567
0.9666666666666667


/Users/Syed/anaconda/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


## PCA projection to 2D

In [6]:

pca =PCA(n_components =2)
principalComponents = pca.fit_transform(x_norm)
pdf = pd.DataFrame(data=principalComponents, columns = ['pc1', 'pc2'])

# pdf

In [7]:
finaldf = pd.concat([pdf,df[['target']]], axis =1)
finaldf.head()

pc1       pc2       target
0 -2.264542  0.505704  Iris-setosa
1 -2.086426 -0.655405  Iris-setosa
2 -2.367950 -0.318477  Iris-setosa
3 -2.304197 -0.575368  Iris-setosa
4 -2.388777  0.674767  Iris-setosa

In [8]:
#NB scikit learn
X, y = load_iris(return_X_y=True)
# X = StandardScaler().fit_transform(X)
# pca =PCA(n_components =2)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train = X_train*10
X_test = X_test *10


In [9]:
X_test[:5]

array([[58., 28., 51., 24.],
       [60., 22., 40., 10.],
       [55., 42., 14.,  2.],
       [73., 29., 63., 18.],
       [50., 34., 15.,  2.]])

In [10]:
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 30 points : 1
0.9666666666666667


In [164]:
gnb = BernoulliNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 30 points : 24
0.2


In [11]:
X, y = load_iris(return_X_y=True)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


In [12]:
x_train = x_train *10
x_test = x_test *10

x_test[:5]

array([[58., 28., 51., 24.],
       [60., 22., 40., 10.],
       [55., 42., 14.,  2.],
       [73., 29., 63., 18.],
       [50., 34., 15.,  2.]])

In [13]:
df = pd.DataFrame(x_train, columns=['f1','f2', 'f3','f4'])

df ['target'] = y_train
# df_mean = df.groupby(['target']).mean()
df_mean = df.groupby(['target']).mean().astype(int)
# df_var = df.groupby(['target']).var()
df_var = df.groupby(['target']).var().astype(int)


In [14]:
df_var.head()

f1  f2  f3  f4
target                
0       13  14   2   1
1       27  10  23   4
2       39  11  30   6

In [15]:
df_mean.head()

f1  f2  f3  f4
target                
0       50  34  14   2
1       58  27  42  13
2       66  29  55  20

In [17]:
#prior probability 
dfp = df.groupby('target').size()
Prior0 = int(dfp[0]/len(df)*100)
Prior1 = int(dfp[1]/len(df)*100)
Prior2 = int(dfp[2]/len(df)*100)
prior_t = [Prior0, Prior1, Prior2]

In [18]:
mean_arr = df_mean.values
var_arr = df_var.values
# x_test = x_test *10
# x_test

In [21]:
ganache_url = "http://127.0.0.1:8545"
web3 = Web3(Web3.HTTPProvider(ganache_url))
web3.isConnected()

True

In [ ]:
abi_train = json.loads('[ { "inputs": [ { "internalType": "int256[]", "name": "feature", "type": "int256[]" }, { "internalType": "int256", "name": "n", "type": "int256" } ], "name": "get_mean", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256[]", "name": "feature", "type": "int256[]" }, { "internalType": "int256", "name": "m", "type": "int256" }, { "internalType": "int256", "name": "n", "type": "int256" } ], "name": "get_var", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "set_mean_var", "outputs": [ { "internalType": "int256", "name": "", "type": "int256" }, { "internalType": "int256", "name": "", "type": "int256" } ], "stateMutability": "nonpayable", "type": "function" } ]')
cont_t = "0xc68179396c40C322e8db2EAd45e12AaF87c3ae52"
cont_train = web3.eth.contract(address=cont_t,abi=abi_train)

In [ ]:
abi_pred = json.loads('[ { "constant": false, "inputs": [ { "name": "x", "type": "int256[]" }, { "name": "v", "type": "int256[]" }, { "name": "m", "type": "int256[]" } ], "name": "a_getparameters1", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [ { "name": "e0", "type": "int256" }, { "name": "e1", "type": "int256" }, { "name": "f0", "type": "int256" }, { "name": "f1", "type": "int256" }, { "name": "g0", "type": "int256" }, { "name": "g1", "type": "int256" }, { "name": "h0", "type": "int256" }, { "name": "h1", "type": "int256" }, { "name": "Prior0", "type": "int256" }, { "name": "Prior1", "type": "int256" } ], "name": "e_exponent", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [ { "name": "v", "type": "int256[]" }, { "name": "k", "type": "uint256" } ], "name": "mux", "outputs": [ { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "a_setparameters1", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "set_exponent", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" } ]')
cont_p = "0x0d76d89884357E61cbD4E8B63258Be6BFD005BAd"
cont_pred = web3.eth.contract(address=cont_p,abi=abi_pred)

In [ ]:
#grit
account1 = "0xdd617f9D5120b7b30E4C502fdd6b13dCf286A300"
private_key1="c00b36dc1777e7fda60ff1f55b57c3f51b18c0c16fe44724e451ed062a173d74"
account2 = "0x8883f1016E727C8fE93C1Df471f102bBbAF2B910"
private_key2="8d70f54549b5fb7c04fc016cc88c447fc81aff3af3065c696aee1b529fbc8ba5"

In [ ]:
def get_mean(feature, n, account, private_key,contract):
    nonce = web3.eth.getTransactionCount(account)
    tx = cont_train.function.get_mean(
        feature,n
    ).buildTransaction({
    'gas': 3000000,
    'gasPrice': web3.toWei('10','gwei'),
    'from': account,
    'nonce': nonce
    })
    signed_tx = web3.eth.account.signTransaction(tx, private_key=private_key)
    tx_hash = web3.eth.sendRawTransaction(signed_tx.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)

def get_variance(feature, n, account, private_key,contract):
    nonce = web3.eth.getTransactionCount(account)
    tx = cont_train.function.get_var(
        feature,mean.n
    ).buildTransaction({
    'gas': 3000000,
    'gasPrice': web3.toWei('10','gwei'),
    'from': account,
    'nonce': nonce
    })
    signed_tx = web3.eth.account.signTransaction(tx, private_key=private_key)
    tx_hash = web3.eth.sendRawTransaction(signed_tx.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    
def get_class1(features,means, variances, account, private_key,contract):
    nonce = web3.eth.getTransactionCount(account)
    tx = cont_pred.function.get_var(
        feature,mean.n
    ).buildTransaction({
    'gas': 3000000,
    'gasPrice': web3.toWei('10','gwei'),
    'from': account,
    'nonce': nonce
    })
    signed_tx = web3.eth.account.signTransaction(tx, private_key=private_key)
    tx_hash = web3.eth.sendRawTransaction(signed_tx.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    
def get_class2(features,means,variances, account, private_key,contract):
    nonce = web3.eth.getTransactionCount(account)
    tx = cont_pred.function.get_var(
        feature,mean,n
    ).buildTransaction({
    'gas': 3000000,
    'gasPrice': web3.toWei('10','gwei'),
    'from': account,
    'nonce': nonce
    })
    signed_tx = web3.eth.account.signTransaction(tx, private_key=private_key)
    tx_hash = web3.eth.sendRawTransaction(signed_tx.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)

def get_probability(A0,A1,B0,B1,C0,C1,D0,D1,Prior0,Prior1, private_key,contract):
    nonce = web3.eth.getTransactionCount(account)
    tx = cont_pred.function.get_var(
        A0,A1,B0,B1,C0,C1,D0,D1,Prior0,Prior1
    ).buildTransaction({
    'gas': 3000000,
    'gasPrice': web3.toWei('10','gwei'),
    'from': account,
    'nonce': nonce
    })
    signed_tx = web3.eth.account.signTransaction(tx, private_key=private_key)
    tx_hash = web3.eth.sendRawTransaction(signed_tx.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)

def compare(A,B):
    if(A>B): return A
    else: return B

In [190]:
pca =PCA(n_components =)
pca.fit(x_train,pca)

df_train = pca.transform(x_train).astype(int)
df_test = pca.transform(x_test).astype(int)
df = pd.DataFrame(df_train, columns=['f1','f2','f3','f4'])
df ['target'] = y_train
# df_mean = df.groupby(['target']).mean()
df_mean = (df.groupby(['target']).mean()).astype(int)
# df_var = df.groupby(['target']).var()
df_var = (df.groupby(['target']).var()).astype(int)


In [191]:
mean_arr = df_mean.values
var_arr = df_var.values

In [192]:
pred = classification(df_test,mean_arr,var_arr,prior_t)
pred

<ipython-input-175-fa32dfeb075b>:21: RuntimeWarning: divide by zero encountered in double_scalars
  ex = float(C0/D0)
<ipython-input-175-fa32dfeb075b>:22: RuntimeWarning: divide by zero encountered in long_scalars
  out = (A0/B0)*pow(e,-1*ex)
<ipython-input-175-fa32dfeb075b>:22: RuntimeWarning: invalid value encountered in double_scalars
  out = (A0/B0)*pow(e,-1*ex)


array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [193]:
print(accuracy_score(y_test,pred))

0.2


In [ ]:
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(1,1,1)
ax.set_xlabel('Component 1', fontsize =15)
ax.set_ylabel('Component 2', fontsize =15)

ax.set_title('2 COmponent PCA', fontsize =20)

targets = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
colors =['r','b','g']
for target, color in zip(targets,colors):
    indicesToKeep = finaldf['target']==target
    ax.scatter(finaldf.loc[indicesToKeep,'pc1'], finaldf.loc[indicesToKeep,'pc2'], c=color, s=50)