## Loading the Dataset

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_diabetes
import matplotlib.pyplot as plt
# df['target']                             

In [2]:
df = pd.read_csv("diabetes.csv")
target = np.array(df['Outcome'].values)
target.shape

(768,)

In [3]:
features = np.array(df.drop(columns = ['Outcome']))
features.shape

(768, 8)

In [4]:
features = StandardScaler().fit_transform(features)

In [5]:
x_train,x_test, y_train, y_test = train_test_split(features,target,test_size=0.2, random_state=1)
x_train = (StandardScaler().fit_transform(x_train)*100).astype(int)
x_test = (StandardScaler().fit_transform(x_test)*100).astype(int)

In [6]:
gnb = GaussianNB()
y_pred = gnb.fit(x_train, y_train).predict(x_test)
print("Number of mislabeled points out of a total %d points : %d" % (x_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 154 points : 36
0.7662337662337663


In [7]:
gnb = BernoulliNB()
y_pred = gnb.fit(x_train, y_train).predict(x_test)
print("Number of mislabeled points out of a total %d points : %d" % (x_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 154 points : 40
0.7402597402597403


In [8]:
from sklearn.decomposition import PCA
pca =PCA(n_components =2)
PC_train = pca.fit_transform(x_train)
PC_test = pca.fit_transform(x_test)
# pdf = pd.DataFrame(data=principalComponents, columns = ['pc1', 'pc2'])

# pdf

In [9]:
gnb = GaussianNB()
y_pred = gnb.fit(PC_train, y_train).predict(PC_test)
print("Number of mislabeled points out of a total %d points : %d" % (PC_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 154 points : 68
0.5584415584415584


In [10]:
gnb = BernoulliNB()
y_pred = gnb.fit(PC_train, y_train).predict(PC_test)
print("Number of mislabeled points out of a total %d points : %d" % (PC_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 154 points : 72
0.5324675324675324


In [12]:
def mux1(v,k):
    x = 1
#     print(type(v))
    for i in range(len(v)):
        if(i==k): continue
        else:  x = x* v[i]
    return x

def compute_param(x,m,v):
    B0=1; C0 =1.0;  A0=1; e = 2.718
    c = np.zeros(len(v));
    for i in range(len(v)):
        B0 = B0* v[i]
        c[i] = (x[i]-m[i])*(x[i]-m[i])   
    D0 = B0
    for i in range(len(c)):
        C0 = C0+c[i]*mux1(v,i)
#     print(A0,B0,C0,D0)    
    ex = float(C0/D0)
#     out = (A0/B0)*pow(e,-1*ex)
#     return(out) 
    return (A0,B0,C0,D0)

# def exponent(x, m1,m2, v1,v2, Prior0,Prior1):
#         x1=1; x2=2
#         A0,B0,C0,D0 = compute_param(x,m1,v1)
#         A1,B1,C1,D1 = compute_param(x,m2,v2)
#         print(A0,B0,C0,D0)
#         print(A1,B1,C1,D1)
#         A = A0*B1
#         B = B0*A1
#         C = (C0*D1)-(C1*D0)
#         D = D0*D1
#         Q = int(C/D)
#         R = C%D;
#         Enum=19
#         Eden=7
#         edenR = 24*(D*D*D*D)
#         enumR = 24*D*D*D*D+ R*24*D*D*D+R*R*12*D*D+R*R*R*4*D+R*R*R*R
#         if(Q>=0):
#             P0 = A*1*edenR*Prior0*Prior0
#             P1 = B*1000*enumR*Prior1*Prior1
#         else:
#             P0 = A*1000*edenR*Prior0*Prior0
#             P1 = B*1*enumR*Prior1*Prior1
#         if(P0>P1): return 0
#         else : return 1
        
def exponent(x, m1,m2, v1,v2, Prior0,Prior1):
        A0,B0,C0,D0 = compute_param(x,m1,v1)
        A1,B1,C1,D1 = compute_param(x,m2,v2)
        print(A0,B0,C0,D0)
        print(A1,B1,C1,D1)
        A = A0*B1
        B = B0*A1   
        print("value of A and B are :",A,B)
        C = (C0*D1)-(C1*D0)
        D = D0*D1
        print("Value of C and D are:",C,D)
        Q = C//D
        R = int(C%D);
        print("Value of Q and R are : ", Q,R)
#         print(Q,R)
        
        Enum=19
        Eden=7
        
        edenR = 24*(D*D*D*D)
        enumR = 24*D*D*D*D+ R*24*D*D*D+R*R*12*D*D+R*R*R*4*D+R*R*R*R
         
        if(Q>=0):
            print("Q is greater")
            P0 = A*1*edenR*Prior0*Prior0
            P1 = B*1000*enumR*Prior1*Prior1
        else:
            print("Q is smaller")
            P0 = A*1000*edenR*Prior0*Prior0
            P1 = B*1*enumR*Prior1*Prior1
        if(P0>P1): 
#             print(0)
            return 0
        else : 
#             print(1)
            return 1

In [13]:
df = pd.read_csv("diabetes.csv")
target = np.array(df['Outcome'].values)
features = np.array(df.drop(columns = ['Outcome']))
dfp = df.groupby('Outcome').size()
Prior0 = int(dfp[0]/len(df)*100)
Prior1 = int(dfp[1]/len(df)*100)

In [14]:
Prior1

34

In [65]:
x_train,x_test, y_train, y_test = train_test_split(features,target,test_size=0.2, random_state=1)
x_train = (StandardScaler().fit_transform(x_train)*10).astype(int)
x_test = (StandardScaler().fit_transform(x_test)*10).astype(int)

In [79]:
gnb = GaussianNB()
y_pred = gnb.fit(x_train, y_train).predict(x_test)
print("Number of mislabeled points out of a total %d points : %d" % (x_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 154 points : 38
0.7532467532467533


In [80]:
x_train

array([[15,  7,  5, ...,  7,  5,  5],
       [18,  2, -3, ..., 12,  0,  3],
       [ 9, -6,  2, ...,  7, -7,  9],
       ...,
       [26,  1, 10, ..., 15,  3,  7],
       [ 0, 15,  1, ..., 15,  0, -6],
       [15, -6,  3, ...,  1,  6, 10]])

In [81]:
x_test

array([[  9,   4,   2, ...,  -7,   4,  15],
       [ -8,   9,  -5, ...,  -7,  -9,  -9],
       [  6,  -3,  -5, ...,  -8,  -8,  -5],
       ...,
       [ 12,  20,   4, ...,  17, -10,   8],
       [  3,   4,   6, ..., -37,   3,  31],
       [  0,  -8, -39, ...,  -5,   3,  -1]])

In [82]:
df_new = pd.DataFrame(x_train,columns=['f1','f2','f3','f4','f5','f6','f7','f8'])
df_new['Outcome'] = y_train
df_mean = df_new.groupby(['Outcome']).mean().astype(int)
df_var = df_new.groupby(['Outcome']).var().astype(int)
mean = df_mean.values
var = df_var.values

In [83]:
mean[0]

array([-1, -3,  0,  0,  0, -1, -1, -1])

In [150]:
m1 = mean[0].tolist()
m2 = mean[1].tolist()
v1 = var[0].tolist()
v2 = var[1].tolist()
x = x_test[9].tolist()

In [151]:
print(x,',',m1,',',v1)

[-11, -4, -3, 11, 5, 10, -9, -9] , [-1, -3, 0, 0, 0, -1, -1, -1] , [76, 65, 74, 80, 65, 86, 78, 89]


In [152]:
print(x,',',m2,',',v2)

[-11, -4, -3, 11, 5, 10, -9, -9] , [2, 6, 0, 0, 2, 3, 2, 3] , [114, 81, 123, 112, 133, 84, 114, 83]


In [130]:
var

array([[ 76,  65,  74,  80,  65,  86,  78,  89],
       [114,  81, 123, 112, 133,  84, 114,  83]])

In [77]:
x_test[0]

array([ 9,  4,  2,  1,  4, -7,  4, 15])

In [194]:
import matplotlib.pyplot as plt
import json
from web3 import Web3
# ganache_url = "https://ropsten.infura.io/v3/6072fdc3b95c407caa681f63ebaf72b8"
ganache_url ="http://127.0.0.1:8545"
web3 = Web3(Web3.HTTPProvider(ganache_url))
web3.isConnected()

True

In [200]:
abi = json.loads('[ { "constant": true, "inputs": [], "name": "set_e_exponent1", "outputs": [ { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [ { "name": "b", "type": "int256" }, { "name": "c", "type": "int256" }, { "name": "d", "type": "int256" } ], "name": "reduction", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "print", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "a_setparameters2", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [ { "name": "x", "type": "int256[]" }, { "name": "m", "type": "int256[]" }, { "name": "v", "type": "int256[]" } ], "name": "a_getparameters1", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [ { "name": "x", "type": "int256[]" }, { "name": "m", "type": "int256[]" }, { "name": "v", "type": "int256[]" } ], "name": "a_getparameters2", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "a_setparameters1", "outputs": [ { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" }, { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [ { "name": "v", "type": "int256[]" }, { "name": "k", "type": "uint256" } ], "name": "mux", "outputs": [ { "name": "", "type": "int256" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [ { "name": "Prior0", "type": "int256" }, { "name": "Prior1", "type": "int256" } ], "name": "get_e_exponent1", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" } ]')
cont= '0xD1062fe3389848618526B005303E2392d0b798A6'
contract= web3.eth.contract(address=cont,abi=abi)

account1 = "0xdd617f9D5120b7b30E4C502fdd6b13dCf286A300"
privatekey1 = "c00b36dc1777e7fda60ff1f55b57c3f51b18c0c16fe44724e451ed062a173d74"
account2 = "0x8883f1016E727C8fE93C1Df471f102bBbAF2B910"
privatekey2="8d70f54549b5fb7c04fc016cc88c447fc81aff3af3065c696aee1b529fbc8ba5"
account3 = "0xd39fdd79c3b5b0c411366D5A64ba26E423e1cF61"
privatekey3="3f3bcef69f8cef4bb28953eebe0b11c40fca5b4ce8c9665d3647afd067050952"

In [201]:
def getparams1(a,b,c,account1,privatekey1):
    nonce = web3.eth.getTransactionCount(account1)
    transaction = contract.functions.a_getparameters1(
        a,b,c
         ).buildTransaction({
        'gas': 3000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account1,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey1)
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    return tx_receipt.gasUsed

In [202]:
def getparams2(a,b,c,account2,privatekey2):
    nonce = web3.eth.getTransactionCount(account2)
    transaction = contract.functions.a_getparameters2(
        a,b,c
         ).buildTransaction({
        'gas': 3000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account2,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey2)
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    return tx_receipt.gasUsed

In [203]:
def get_e_expon(p0,p1,account3,privatekey3):
    nonce = web3.eth.getTransactionCount(account3)
    transaction = contract.functions.get_e_exponent1(
        p0,p1
         ).buildTransaction({
        'gas': 3000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account3,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(transaction, private_key=privatekey3)
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    return tx_receipt.gasUsed

In [204]:
x = contract.functions.set_e_exponent1().call()
x

1

In [160]:
m1 = mean[0].tolist()
m2 = mean[1].tolist()
v1 = var[0].tolist()
v2 = var[1].tolist()
pred = np.zeros(x_test.shape[0])
for i in range(x_test.shape[0]): 
    x = x_test[i].tolist()
    getparams1(x,m1,v1,account1,privatekey1)
    getparams2(x,m2,v2,account2,privatekey2)
    get_e_expon(Prior0,Prior1,account3,privatekey3)
    pred[i] = contract.functions.set_e_exponent1().call()
#     print(contract.functions.set_e_exponent1().call())

0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
1
0
0
0
1
0
0
0
0
1
0
1
0
1
0
1
0
1
0
0
0
1
0
0
0
1
0
0
1
1
0
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
0
0
1
1
1
1
0
0
1
0
1
0
0
1
1
0
0
0
0
1
0
1
0
0
1
0
0
0
1
0
0
0
1
0
0
1
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
1
0
1
0
1
0
0
0
0
1
0
0
1
0
0
1
1
1
0
0
0
0
0
1
0
1


In [149]:
pred[9]

1.0

In [164]:
from sklearn.decomposition import PCA
for i in range(2,9):
    pca =PCA(n_components =i)
    pca.fit(x_train,pca)
    PC_train = pca.transform(x_train)
    PC_test = pca.transform(x_test)
    gnb = GaussianNB()
    y_pred = gnb.fit(PC_train, y_train).predict(PC_test)
    print("Number of mislabeled points out of a total %d points : %d" % (PC_test.shape[0], (y_test != y_pred).sum()))
    print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 154 points : 40
0.7402597402597403
Number of mislabeled points out of a total 154 points : 43
0.7207792207792207
Number of mislabeled points out of a total 154 points : 42
0.7272727272727273
Number of mislabeled points out of a total 154 points : 38
0.7532467532467533
Number of mislabeled points out of a total 154 points : 44
0.7142857142857143
Number of mislabeled points out of a total 154 points : 45
0.7077922077922078
Number of mislabeled points out of a total 154 points : 48
0.6883116883116883


In [161]:
accuracy_score(pred, y_test)

0.7337662337662337

## PCA

In [242]:
pca =PCA(n_components =7)
pca.fit(x_train,pca)
PC_train = (pca.transform(x_train)).astype(int)
PC_test = (pca.transform(x_test)).astype(int)
df_pc = pd.DataFrame(PC_train, columns=['f1','f2','f3','f4','f5','f6','f7'])
df_pc  ['target'] = y_train
df_mean = df_pc.groupby(['target']).mean().astype(int)
df_var = df_pc.groupby(['target']).var().astype(int)
mean = df_mean.values
var = df_var.values

In [243]:
print(PC_test[0].tolist(),',', mean[0].tolist(),',',var[0].tolist())

[5, 15, 5, 1, -6, -5, 5] , [-3, -1, -1, 0, 0, -1, 0] , [144, 136, 78, 57, 48, 43, 32]


In [244]:
print(PC_test[0].tolist(),',', mean[1].tolist(),',',var[1].tolist())

[5, 15, 5, 1, -6, -5, 5] , [6, 3, 2, -1, 1, 2, 0] , [180, 151, 103, 95, 86, 82, 44]


In [245]:
var

array([[144, 136,  78,  57,  48,  43,  32],
       [180, 151, 103,  95,  86,  82,  44]])

In [246]:
m1 = mean[0].tolist()
m2 = mean[1].tolist()
v1 = var[0].tolist()
v2 = var[1].tolist()
pred = np.zeros(PC_test.shape[0])
for i in range(PC_test.shape[0]): 
    x = PC_test[i].tolist()
    getparams1(x,m1,v1,account1,privatekey1)
    getparams2(x,m2,v2,account2,privatekey2)
    get_e_expon(Prior0,Prior1,account3,privatekey3)
    pred[i] = contract.functions.set_e_exponent1().call()

In [247]:
accuracy_score(pred, y_test)

0.538961038961039