## Loading the Dataset

In [20]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_diabetes
import matplotlib.pyplot as plt
# df['target']                             

In [21]:
df = pd.read_csv("heart.csv")
df.head()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [22]:
# df['oldpeak'] - df['oldpeak']*10
target = np.array(df['target'].values)
target.shape

(303,)

In [23]:
features = np.array(df.drop(columns = ['target']))
features.shape

(303, 13)

In [24]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [25]:
x_train,x_test, y_train, y_test = train_test_split(features,target,test_size=0.2, random_state=0)
x_train = (StandardScaler().fit_transform(x_train)*100).astype(int)
x_test = (StandardScaler().fit_transform(x_test)*100).astype(int)
# x_test

In [26]:
x_train.shape

(242, 13)

In [27]:
gnb = GaussianNB()
y_pred = gnb.fit(x_train, y_train).predict(x_test)
print("Number of mislabeled points out of a total %d points : %d" % (x_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 61 points : 12
0.8032786885245902


In [28]:
gnb = BernoulliNB()
y_pred = gnb.fit(x_train, y_train).predict(x_test)
print("Number of mislabeled points out of a total %d points : %d" % (x_test.shape[0], (y_test != y_pred).sum()))
print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 61 points : 9
0.8524590163934426


In [29]:
# x_test= x_test.astype(int)
# x_train = x_train.astype(int)

In [30]:
from sklearn.decomposition import PCA
for i in range(2,14):
    pca =PCA(n_components =i)
    pca.fit(x_train,pca)
    PC_train = pca.transform(x_train)
    PC_test = pca.transform(x_test)
    gnb = GaussianNB()
    y_pred = gnb.fit(PC_train, y_train).predict(PC_test)
    print("Number of mislabeled points out of a total %d points : %d" % (PC_test.shape[0], (y_test != y_pred).sum()))
    print(accuracy_score(y_test, y_pred))

Number of mislabeled points out of a total 61 points : 8
0.8688524590163934
Number of mislabeled points out of a total 61 points : 10
0.8360655737704918
Number of mislabeled points out of a total 61 points : 8
0.8688524590163934
Number of mislabeled points out of a total 61 points : 11
0.819672131147541
Number of mislabeled points out of a total 61 points : 12
0.8032786885245902
Number of mislabeled points out of a total 61 points : 14
0.7704918032786885
Number of mislabeled points out of a total 61 points : 14
0.7704918032786885
Number of mislabeled points out of a total 61 points : 14
0.7704918032786885
Number of mislabeled points out of a total 61 points : 13
0.7868852459016393
Number of mislabeled points out of a total 61 points : 13
0.7868852459016393
Number of mislabeled points out of a total 61 points : 13
0.7868852459016393
Number of mislabeled points out of a total 61 points : 13
0.7868852459016393


In [31]:
def mux1(v,k):
    x = 1
#     print(type(v))
    for i in range(len(v)):
        if(i==k): continue
        else:  x = x* v[i]
    return x

def compute_param(x,m,v):
    B0=1; C0 =1.0;  A0=1; e = 2.718
    c = np.zeros(len(v));
    for i in range(len(v)):
        B0 = B0* v[i]
        c[i] = (x[i]-m[i])*(x[i]-m[i])   
    D0 = B0
    for i in range(len(c)):
        C0 = C0+c[i]*mux1(v,i)
#     print(A0,B0,C0,D0)    
    ex = float(C0/D0)
#     out = (A0/B0)*pow(e,-1*ex)
#     return(out) 
    return (A0,B0,C0,D0)
        
def exponent(x, m1,m2, v1,v2, Prior0,Prior1):
        A0,B0,C0,D0 = compute_param(x,m1,v1)
        A1,B1,C1,D1 = compute_param(x,m2,v2)
        A = A0*B1
        B = B0*A1   
        C = (C0*D1)-(C1*D0)
        D = D0*D1
        
        
        Q = int(C/D)
        R = C%D;
        
        Enum=19
        Eden=7
        
        edenR = 24*(D*D*D*D)
        enumR = 24*D*D*D*D+ R*24*D*D*D+R*R*12*D*D+R*R*R*4*D+R*R*R*R
        
        if(Q>=0):
            P0 = A*1*edenR*Prior0*Prior0
            P1 = B*1000*enumR*Prior1*Prior1
        else:
            P0 = A*1000*edenR*Prior0*Prior0
            P1 = B*1*enumR*Prior1*Prior1
        if(P0>P1): 
            print(0)
            return 0
        else : 
            print(1)
            return 1


In [176]:
df = pd.read_csv("heart.csv")
target = np.array(df['target'].values)
features = np.array(df.drop(columns = ['target']))


In [177]:
# df_mean = df.groupby(['target']).mean()
df_mean = df.groupby(['target']).mean().astype(int)
# df_var = df.groupby(['target']).var()
df_var = df.groupby(['target']).var().astype(int)
dfp = df.groupby('target').size()
Prior0 = int(dfp[0]/len(df)*100)
Prior1 = int(dfp[1]/len(df)*100)

In [180]:
x_train,x_test, y_train, y_test = train_test_split(features,target,test_size=0.2, random_state=1)
x_train = (StandardScaler().fit_transform(x_train)*100).astype(int)
x_test = (StandardScaler().fit_transform(x_test)*100).astype(int)

In [182]:
df = pd.DataFrame(x_train,columns=['f1','f2','f3','f4','f5','f6','f7','f8','f9','f10','f11','f12','f13'])
df_mean = df.groupby(['target']).mean().astype(int)
# df_var = df.groupby(['target']).var()
df_var = df.groupby(['target']).var().astype(int)

<bound method NDFrame.head of       f1   f2   f3   f4   f5   f6   f7   f8   f9  f10  f11  f12  f13
0    -27   66  197  -77 -117  -41 -102  172  -68  -93  -66  -72 -211
1    137 -150   99  118   59  -41   88   95  -68  -93   96   27  -47
2     27   66   99  107 -234  239   88   99  -68  -75   96   27  116
3     27   66    2  130  -27  -41 -102   61  -68  -93   96   27  -47
4    -48 -150    2  -65   -4  -41   88   53  -68    7   96  -72  -47
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
237  148   66   99  279   53  239 -102    2  146   52  -66  -72  116
238 -103   66  -95   61  121  -41 -102  -10  146  -93  -66  226  116
239 -278   66    2   -7  -82  -41 -102  223  -68  -93   96  -72  -47
240  -38   66  -95   49  102  -41   88   99  146   52   96  -72  116
241   -5   66   99  107  -27  -41 -102   65  -68   52   96  -72  116

[242 rows x 13 columns]>

In [164]:
pca =PCA(n_components =3)
pca.fit(x_train,pca)
PC_train = (pca.transform(x_train)).astype(int)
PC_test = (pca.transform(x_test)).astype(int)
# print(PC_train)
df = pd.DataFrame(PC_train, columns=['f1','f2','f3'])
df ['target'] = y_train
# x_train = (x_train*100).astype(int)
# x_test = (x_test*100).astype(int)

In [165]:
# df_mean = df.groupby(['target']).mean()
df_mean = df.groupby(['target']).mean().astype(int)
# df_var = df.groupby(['target']).var()
df_var = df.groupby(['target']).var().astype(int)

In [166]:
dfp = df.groupby('target').size()
Prior0 = int(dfp[0]/len(df)*100)
Prior1 = int(dfp[1]/len(df)*100)


In [167]:
mean = df_mean.values
mean

array([[123, -23, -22],
       [-99,  18,  18]])

In [168]:
var = df_var.values
var


array([[18367, 14677, 13107],
       [11646, 15800, 11250]])

In [169]:
PC_test[0]

array([337,  81, 163])

In [170]:
pred = []
for i in range(x_test.shape[0]):
    pred.append(exponent(PC_test[i], mean[0],mean[1], var[0],var[1], Prior0,Prior1))


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


<ipython-input-31-223832a16549>:13: RuntimeWarning: overflow encountered in long_scalars
  B0 = B0* v[i]
<ipython-input-31-223832a16549>:57: RuntimeWarning: overflow encountered in long_scalars
  D = D0*D1
<ipython-input-31-223832a16549>:71: RuntimeWarning: overflow encountered in long_scalars
  edenR = 24*(D*D*D*D)
<ipython-input-31-223832a16549>:72: RuntimeWarning: overflow encountered in long_scalars
  enumR = 24*D*D*D*D+ R*24*D*D*D+R*R*12*D*D+R*R*R*4*D+R*R*R*R
<ipython-input-31-223832a16549>:76: RuntimeWarning: overflow encountered in long_scalars
  P0 = A*1*edenR*Prior0*Prior0
<ipython-input-31-223832a16549>:77: RuntimeWarning: overflow encountered in long_scalars
  P1 = B*1000*enumR*Prior1*Prior1
<ipython-input-31-223832a16549>:79: RuntimeWarning: overflow encountered in long_scalars
  P0 = A*1000*edenR*Prior0*Prior0


In [171]:
predicted = np.array(pred)
accuracy_score(predicted,y_test)

0.5245901639344263

In [106]:
print(predicted)

[0 1 1 0 0 0 0 1 0 1 1 0 1 0 0 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 0 1 0
 1 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1]


In [96]:
print(y_test)

[0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1
 0 0 1 1 0 1 0 0 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1]
